import React, {
  useState,
  useEffect,
  useLayoutEffect,
  useCallback
} from 'react';
import { TouchableOpacity, Text } from 'react-native';
import { GiftedChat } from 'react-native-gifted-chat';
import {
  collection,
  addDoc,
  orderBy,
  query,
  onSnapshot
} from 'firebase/firestore';
import { signOut } from 'firebase/auth';

import { auth, database } from '../config/firebase';

export default function Chat({ route, navigation }) {
  console.log("Screens chat screen");
  const { myID, otherID, myRole } = route.params;
  const [messages, setMessages] = useState([]);

  const onSignOut = () => {
    signOut(auth).catch(error => console.log('Error logging out: ', error));
  };
  //function to handle logout action
  useLayoutEffect(() => {
    navigation.setOptions({
      headerRight: () => (
        <TouchableOpacity
          style={{
            marginRight: 10
          }}
          onPress={onSignOut}
        >
          <Text>Logout</Text>
        </TouchableOpacity>
      )
    });
  }, [navigation]);

  // useEffect(() => {
  //   setMessages([

  // }, []);
  if (myRole==1){
    var chatRoom = otherID + "_" + myID; 
  }
  else{
    var chatRoom = myID + "_" + otherID;
  }
  console.log(chatRoom);
  useEffect(() => {
    //const collectionRef = collection(database, 'chats');
    const collectionRef = collection(database, chatRoom);
    const q = query(collectionRef, orderBy('createdAt', 'desc'));

    const unsubscribe = onSnapshot(q, querySnapshot => {
      setMessages(
        querySnapshot.docs.map(doc => ({
          _id: doc.data()._id,
          createdAt: doc.data().createdAt.toDate(),
          text: doc.data().text,
          user: doc.data().user
        }))
      );
    });

    return () => unsubscribe();
  }, []);
  //sends a message and uses the useCallback hook and will store messages in firebase database chats.
  const onSend = useCallback((messages = []) => {
    setMessages(previousMessages =>
      GiftedChat.append(previousMessages, messages)
    );
    const { _id, createdAt, text, user } = messages[0];
    //uses the addDoc method from firestone to create a new document with an autogenerated id when a new message is sent.
    addDoc(collection(database, chatRoom), {
      _id,
      createdAt,
      text,
      user
    });
  }, []);
//Using the GiftedChat component and its different prop
  return (
    <GiftedChat
      messages={messages} //messages prop to display messages
      showAvatarForEveryMessage={true}
      onSend={messages => onSend(messages)}
      user={{
        _id: auth?.currentUser?.email,
        avatar: 'https://i.scdn.co/image/ab6761610000e5ebb0527c32ded4594c557f613a'
      }}
    />
  );
}
